name: Build DLL

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc, i686-pc-windows-msvc

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build DLL (Debug)
        run: |
          cargo build --target x86_64-pc-windows-msvc
          cargo build --target i686-pc-windows-msvc

      - name: Build DLL (Release)
        run: |
          cargo build --release --target x86_64-pc-windows-msvc
          cargo build --release --target i686-pc-windows-msvc

      - name: Prepare Files
        run: |
          mkdir debug_zip\x64
          mkdir debug_zip\x86
          copy target\x86_64-pc-windows-msvc\debug\coldloader.dll debug_zip\x64\
          copy target\i686-pc-windows-msvc\debug\coldloader.dll debug_zip\x86\
          copy coldloader.EXAMPLE.ini debug_zip\

          mkdir release_zip\x64
          mkdir release_zip\x86
          copy target\x86_64-pc-windows-msvc\release\coldloader.dll release_zip\x64\
          copy target\i686-pc-windows-msvc\release\coldloader.dll release_zip\x86\
          copy coldloader.EXAMPLE.ini release_zip\

      - name: Package Debug
        run: Compress-Archive -Path debug_zip\* -DestinationPath coldloader-debug.zip

      - name: Package Release
        run: Compress-Archive -Path release_zip\* -DestinationPath coldloader-release.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            coldloader-debug.zip
            coldloader-release.zip
